spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
orders:
  scheduler:
    interval-ms: 300000
